[project]
name = "purbaya-net"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "rapidfuzz>=3.14.1",
    "requests>=2.32.5",
    "spacy>=3.8.7",
]
